#!/bin/sh

LOCK="/tmp/brightness.lock"

mkdir $LOCK 2> /dev/null || exit

NOTIF_ID=24444

notif() {
	dunstify -t 2000 -r $NOTIF_ID  "Bright: $1%"   "$(getProgressString 11 "🌞" "🌚" $1)"
}

up() {
	light -A 5
}
down() {
	light -U 5
}

$1 2> /dev/null

bright=$(light -G)
bright=${bright%%.*}

$2 $bright

rm -r $LOCK

