#!/bin/sh

LOCK="/tmp/brightness.lock"

mkdir $LOCK 2> /dev/null || exit

notif() {
	notify-send \
		-t 2000 \
		-h string:x-canonical-private-synchronous:brightness-notify \
		"Bright: $1%" \
		"$(progress 11 "🌞" "🌚" $1)"
}

up() {
	light -A 5
}
down() {
	light -U 5
}

$1 2> /dev/null

bright=$(light -G)
bright=${bright%%.*}

$2 $bright

rm -r $LOCK

