#!/bin/sh

LOCK="/tmp/volume.lock"

mkdir $LOCK 2> /dev/null || exit

notif() {
	volume=$1
	[ "$2" = "off" ] && muted="🔇" || muted="🔊"
	notify-send \
		-t 2000 \
		-h string:x-canonical-private-synchronous:volume-notify \
		"Volume: $volume% $muted" \
		"$(progress 11 "🔴" "⭕" $volume)"
}

toggle() {
	amixer sset Master toggle
	canberra-gtk-play -i audio-volume-change &
}
up() {
	amixer sset Master 5%+
	canberra-gtk-play -i audio-volume-change &
}
down() {
	amixer sset Master 5%-
	canberra-gtk-play -i audio-volume-change &
}
show() {
	amixer sget Master
}

$2 $($1 | tail -1 | awk '{print $5" "$6}' | sed -e "s/[^0-9|a-z| ]*//g")

rm -r $LOCK

